include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - packages/jellyfin_api/lib/src/generated/**
    - build/**
    - android/**
    - ios/**
    - windows/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_final_locals: true
    avoid_print: true
    unawaited_futures: true
    always_declare_return_types: true
